apiVersion: v1
kind: Service
metadata:
  labels:
    app: dummy
  name: dummy
spec:
  ports:
  - name: http
    port: 8011
    protocol: TCP
    targetPort: 8011
  selector:
    app: dummy

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dummy
  name: dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      labels:
        app: dummy
    spec:
      containers:
        - image: "anzemarinko/kitt4sme.dummy:0.1"
          imagePullPolicy: IfNotPresent
          name: dummy
          ports:
          - containerPort: 8011
            name: http
          env:
          - name: "ORION_BASE_URL"
            value: "http://orion:1026"
