apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
data:
  ## Server properties
  # Run server without TLS
  server.insecure: "true"
  # Disable client authentication
  server.disable.auth: "true"
  # Set the logging level. One of: debug|info|warn|error (default "info")
  server.log.level: "debug"
