apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress-policy.yaml
- opa.yaml
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.3/controller.yaml
- secrets

secretGenerator:
- name: opa-policy
  files:
  - rego/main.rego
  - config.keys.rego=rego/config/keys.rego
  - fiware.service.rego=rego/fiware/service.rego
