apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- fiware-ingress-policy.yaml
- opa.yaml

secretGenerator:
- name: opa-policy
  files:
  - rego/main.rego
  - config.keys.rego=rego/config/keys.rego
  - fiware.service.rego=rego/fiware/service.rego
