apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: admin-password
  namespace: default
spec:
  encryptedData:
    password: AgAYc0+oNREP7LD6mnnIbi51pZu7N58V9GSVnPA6bAFZlytZYG7VJT8qDdV6ss2wft7dTXYTeB6qsCvbs5Ilwaj+Y+dN5opNTq6GrQfZQV9wY2LdBl6ZcADq2VIU6ziHuFmfuty5U1c4bqBPDZxvHPNcmYXpmlFM5X6NdyPBym3zs9WQiiH8xip1n4gNYf5c3jru/K8F+kfNLU2k3K8h3VtggmrnOwKAl3kMP8s0hDSmFUBLpRP4rCkza+DK3DY3mSmT/Trvb0ZB8iMAWfjydH+7nnUpEZNSWy2dGpPCYbuevT7vNM2CwClZagmW4NHKC/eA4ml5HGPI7l/ESlRxdOSv0G8fN7OimeGC6IHeIoODfQVSSXkACzT+AnxuZKL3c8EkArTjrT62fdQDvFaAjfUBkj48U/uiQ3x6uwvMAqvSG+3ghvWA1D3QKzRKE0DuRd2eM8qGzXyJ0wp/uxooLdwoWFRzTpguq+9l8uDP7IBKuStW4VMDfFiLtfSPoFFG+wSR82OEvws4bz+mKvv8fIS9w6mpOXX0TQWIKVxennBDrDykUQtUIh82w0fzYa5rHBEUdPkC81bj8XSiUR1QTTU8IiAxetwpxVWkSQsP3aN/ePM1HtcVTgGPaU/c4r6lew0cVJRXzYA5bAl2qnxTYDWXgdzIhMV2CdO91+urRS7IUYjIYfgOwzVMvy1sX3sqHM4MGoQ=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: admin-password
      namespace: default
    type: Opaque

