- op: replace
  path: /metadata/name
  value: cncsmart
- op: replace
  path: /spec/source/path
  value: deployment/plat-app-services/cncsmart
- op: replace
  path: /spec/project
  value: plat-app-services
