- op: replace
  path: /metadata/name
  value: mongodb
- op: replace
  path: /spec/source/path
  value: deployment/plat-infra-services/mongodb
- op: replace
  path: /spec/project
  value: plat-infra-services
