apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: plat-app-services
  namespace: argocd
  # Make sure the project can only be deleted if no app references it.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: KITT4SME platform application services
  # Allow manifests to deploy from any Git repos.
  sourceRepos:
  - '*'
  # Allow manifests to deploy to any namespace in the local cluster.
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
