apiVersion: v1
kind: Service
metadata:
  labels:
    app: insight
  name: insight
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: insight

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: insight
  name: insight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insight
  template:
    metadata:
      labels:
        app: insight
    spec:
      imagePullSecrets:
        - name: insight-image
      containers:
        - image: "ghcr.io/avillaj1988/insight_generator:0.1.0"
          imagePullPolicy: IfNotPresent
          name: insight
          ports:
          - containerPort: 8000
            name: http
          volumeMounts:
          - name: insight-config
            mountPath: /app/config.ini
            subPath: config.ini
            readOnly: true
      volumes:
      - name: insight-config
        configMap:
          name: insight-config
