apiVersion: v1
kind: Service
metadata:
  labels:
    app: cncsmart
  name: cncsmart
spec:
  ports:
  - name: http
    port: 8022
    protocol: TCP
    targetPort: 8022
  selector:
    app: cncsmart

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cncsmart
  name: cncsmart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cncsmart
  template:
    metadata:
      labels:
        app: cncsmart
    spec:
      containers:
        - image: "anzemarinko/kitt4sme.cncsmart:0.1"
          imagePullPolicy: IfNotPresent
          name: cncsmart
          ports:
          - containerPort: 8022
            name: http
          env:
          - name: "ORION_BASE_URL"
            value: "http://orion:1026"
