apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgAhMtkQ9tdr+I9zN6/DN07mlZ/Hvom9nHkaYBQ3TLm/gqDFOU2q/4bQH3XQwiF0Bz+7JYuVsBz6r36w67x0hN0Oz2nvGMUq0UilA+glb84bf4bNpE8fzXPTPjL9/avfmuJUEnZ/IPfNMnkC2iEIIGHqHcSZFPLBVK96MNlxKAsGG+3HLOWfFtTm+fLP4EQDlVByoa0G3A+OeFqj1I2SCNh3PPJKqvp6l5qOOVeuOeUvCv8Gv8PABtFacoXsJC5OrUuIrknllxKPaXFLY6u1G6at9Y2LYkcqhhcOXOPsVbH/zW9edeYVO9RRaxkNcre6cBIvOrVJ4GkeJqnrYWbjRdNRq24bO8zpe/Hev3QVw/HlLrHcuZrrEHvYSJSc4Nyz4Sr9xUdlZhRmDmb25OPaNm2YDfZgM9LA9yeRz2YUE7yE0ZRJTo9JGeKZI14aRxicUABf4OaFV0oorVF1doZa9nCTAlPDbSKKSt/X3y3/U3rclHrYybiyCOHbmevEYg1AsvYr663DUa7DdAj6nDU0Ra5J3zCzLc2/UA8SKNLWAnjiPrVbYvbK0Jj13hy0MfuQKN5320xWMpfCT5mx6nnfX91iXdsz6rXhridY/BuZz9bJyqd5GFIQZ3dpwwpMZUyCTh/1dASLV2ZkoSYkhNR33/KmidHqAetX1/CrB6N1LNQ6HtT7NwwsYxEzQ5/CDbpVaeJlUAElJuDKit3H9FLT
    username: AgCB1hK+RQlVZReUYJyWe9np2KpK4/5PDK+jsca4gf9Y/E3oVWfLPL8GbCAez6ykbTllI5ApY1PaWUklzjfdsXZttLR0stlDO0KCBwh28rECzAEfGDOX+WraM1Ou/Ok/Fgf+8NjSJya7YEoiZLyUqNL5PRJsFGyMnF34TP7I0qxrEa9uEcAYsJzdGa+oTEyHplgn5O4D9JEBYu8Wlr86ZTz5cDrBjhIsPKBTANFCwQyB5Ptq9Xngz0v8JKq4Y58xoeEwlhzUdM8lz3YdKyqytcRBZbxgMI+cn4icRStuyev6jlkgylwQx+zlIE9xo08tyGikVd92fL2pyX57QzBOZq30CqDCblctdJRi3jIviSUT+4XFPmOZfcQ7KwYzkvw9miPZ5RxKNGjytJcsEll4VnIsV4bnICT6AHyoWtTzPdb0R3ja4krOT77hUhe/UpF3GTtEcbSb+vrPcJRlkReeiZV8nSqg2d+/5qFzINr9VRpL36U2BtClmT4EUguGcGNN/fEmYBDlXxoj6pxXm6bekbZP/jlW9hjGzBfVTWGXuh30GkmC4yST8/cNZCjzFgXb3fh0C2iZA3hrGyLX1Ao7gocHDo+kctv8SqVhwzrxp41OL4m3sfwg9mLEPvEn7Tyqsanxy+++3u4L2PJbrTXhE6/hv0yj5SoXikNZrgzWGD4bYn6z4A8nPbsuDQ8qVnQR89v5zxqYag==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

