apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgCjvT8MowikhqTBOLPagjRpVeXf8Q+vEDM6sjOiu60cwG/GkAlmW8aCBxx2s/6JpNMRd7xqp8Hzpm98eg3rxa1sxnAqZqAuA3knRPyhKLSOEysYGhJVUNSy4oV1y3ydfTbxhGMWBTsVymg44Xy1ZCT1RfxbS/odunXA0oQ4PCcSff5BdZeyn5nwLavnzvJJmjq2W/mw5rxJt1QEUWkoNR/AtR/wRhZGE0sbOuivgKzsa+IU9KZwr2iqo6MYDcnFC2YLYfipe2F05ml9O6TjJf45eD/rIL3Zsc/kdptsLWWwsA1wKGtbLrbrcBsIyH4cnO1sjlXS9j1e6V8JBMHcncM8tDUQMqj7dZTqqn4zyGhQR8XerQPWtflN2VKxZFRCpq6oGdLDsmLSmsSZl/pl4F797BPGk5J+QjoBcdHUrhczeNpEnb5vZDqWRlH4AQ+PgOr1vuC9ZLbu76Q5rrCIHCF4nF3pRIIN2nv19GM1Yo88CO5oQSK2tooB9r4wXjpDRazet4lCErP3ak87E0mK5UE2X6OLJKk6fSsLH1ISBMCkJRhGtWr0wHsjH1ExLhx9XnH5bfdd/Vbjii2Gr69gJU17ekK6qXEkyDLXzVN1HCMMhQUz78UWsa+vUm81vItyQ2tWlyWKRF+VA+cT+qefxCeh7PoxY6xeSyzEwDs07xb7x3mTYfpObzPzR6OF2XFe0dKiy2jezOQ=
    username: AgCHMyUcA9oamuGEAEkTeZTMDkUYHSPLsZN9qrPaLT/AgWh23wTUlhQ3C8daGWW4teZ3xLTro7U6ZXyYWPpTmehcT6HTXxYX5dpCSC3uB9u6+ObDkYQ8i9jUtP18OgUK/QC7PRFFrY3ZodnOvq+S32yMuzihs+otDyuxjUXXyIuvtyxcKIda82v7ukjj0v0qWmmbvd0Q0i8N1J/keWKf9bx1KSrKwnNvmYiqmCnWW5NA/rQa62cCLk5/SF0RWuCPdSMsx8/XQ8AqQxKkNwyGmB8WYnYgj7iTGGlh4ESEB6K+DZ5/6R49TRMCxGrjtMjKhM+VfMQ1o4OeKJEdLePHi9aNOH8UvEYmM3KIuUsQZKg5KNFqVy0C6RNAlptyoDb6LpsT9qfntdryboFSUkpzH14cjYCfrnOMV0+9EAP/QzRumfnbN9PTPpuNrRhbPxEQD5BdVfWTQb2QYTStoznXrZZG4Dtjx6aBYKxfo8UnqRg99zosxtvgrEi0mJ/UeZaBq99S67F/7vKgbtW5JOY/tpWnTkK7yNSCP/jVcLcZqVRinY5WBoXAsoavdQ3dbCxbtnOMtlyAZwaSVTh/ANYnOH+rLCYMoLF8cYaklUPivSoUKzVkm0dz5R6t99tVhL3XHmm5VMb6TDHhb0ZIPmIQw9sdwb+MB10Rq8M8WPq58mrOWZHVWByqVnA5BbSKqP8zGvDQWRBPow==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

