apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgAh0+3dAQlW8G2rgloO0/WTSq4T4GCJl05lKqCusKDREiG83i1r6fLbK9RYhzarZfqGf5w+Ss+AwnvB1mLB1CY0L+2UZ2uotmeXh37dBPy5C/fqYU6ukTnixNXBVBy9XvwQmzjEUcIQv1n6QU26bs/FnrW8tkJD2moVcRVCLcJ0z8MvaYmx/lmvCGhuQJzyNGMeFVtjc98Q2/12YB5AEA52wg0dw1ken6sfMt2Kw+xpbYlFu80E6+ru7QmID7lq6Mir+Do7Rk1aiiuua4BH1R94o9wbWk2SkhzyvwFghKn7+JMkGSTv+ArJlUG5UeHCvFprghmRctkrfa2tsoSICre7AGGt8oigtzhH1NPmptxj4qnVqU+FPKHGclDCJlbuNdyqLsYvULD5tRSI6tWrb5BmMy/gEicIdf0EgqcAD1MftHA0G9cAF7oYkNi3EgOBiqytYD72DPMD5LPtB+GmsQCP0DCdqGepVIcCHZ+PV0Zg/c2THEnWE6hmvt8UEi78cLIx2enlSdKICTlnRuMxrqtdWn5kTcVda2gwyKNsH/Qg3oYcibDjH/y9tDQo1oYcq5JREFjV+N1jR6FFleAn4uOB7EKTUxj7soGnwTefD18ZYp58R4+R7Krah9bAp6R9SHHj5Sy6OzP/2REmbnWPHoCsIwKyvDY2/yT83KBy9xyW5SWuVTSrcNRS0jzLgiFnyGd7Tf9dlNg=
    username: AgAsGOXs3749cW9SRT0vF0VOzOqklVMCjllUVk7KpukEP5O9AsQDVkUDPLwBCOSykqAGz2rOaIg5/s04R+TlIG5aI8VjxJR0DpBl9nuHvpa5c2xAS2gFNkRybFfCIfuJ49k49aLIzbyyz46sfyQ8dNgaq8R8w8p1D7v/R5/XskVOGWDUB0L7/aS0Xryz1hTxwa7pAFZIWkinyQo5jhISMGzYSAzjby855culyjtEu+sK2of7c+YMvb7k5pXVplrhlVHDBT3il+NtpJ7bWwJLSISelJ5fAmQ9ttKRfN938+vaR+vSAbjYjxX3vZEWh12X3zH2w9oLhI8Y6gpnGJ3hA/cPZqp6ezU6A7d6vYzNiLV1EDS9Asn/oon+Pj3d0qwaLhD3jntxDSIz0f9IgM46BbyIXKk9XT+D3YNx887IhxTfFm5NWddL6AwWpcyr0r//45hn3wPIKucCvOKA6vf0Er/2mLcTNGhcFtmZ9DVpn0KSdfwguhmFvbrFMoMjRW9uK1TQzTCJYhJi54YBjqpVC9NjUbw/AN9QuUfkVXqHJGn3WAvEeqMvZMYQtEc90Dwrt6C+cN+DCVXXAKhycfPvwsD7YIo9eBnCFzY9BfoyEc1/FXH2rFmShd7KFGOlyMXV0NBMSO9VJ9BMNrc4d2UgZpmxtU+4ghT2SCLEY/4fZeYOHkUieFoVtrdiuWP9J9Al/nBT5LI1Tw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

