apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgAsT9USPRFLlyr0cVHW1v0TKUABLriXLFDBY1pISS8ggVx3qOxEoYJ6FS4rBMZYDR4G1AMCaB/j4xep0GyGYn+6ZcWn2FjjcTjXfbmxHkjjY2fCVAHKKLWxNZNSVx0jM6XmRxSgpGtL7nOHKsDbhuJJzQ9P4fDEtyNpMlsEdRMxTIz0D82t6yBh3bekt5A1F9Gg/9CXvmzWI0zfh77FDVgz3yYmkeBf8fbHAF1yNT1l+ArEqLe8Lq+JoA70H9k7YUhS9I7k6vVEakA932chqqmyJ1h+6YzWcoqZjUyPO9Gt4mGwiuqSi0a29hCAoy0ryTyfYEPJjrNqYGi4f9Gcn32nZadHKzhmD1PWI98BQga0n0DS+O+mFaXm89Q278zirWWhCCHkvw7A2RbYYSX3z3ydi3EWNC6XLNgskWG/ZnNDBFCLzglvqJiPSe/uDMt1YQD+O6kiS/EOtUQmIcIEjoUrL/e0njKQunOHXlYCtE/IBA8mcKos5h2nugtqJPukbpa2ang/xfYhzZ24UIfX8Jm1Z2g+yAM9TMQV6GyXF/yTClAmvXxIBkKNhKhHb52Sz5HyWJUdvnAM/oAERI5yNyNScUnSABSALt5owEZwiKvwfsAIiLBdlEnZvIUlepBaOQyAamhKCxNxnFTIB1iTswUKJX7jo90KWMYaSK5XdmkCuNgqoMBD/GnoLSLh9KKZ3AcFaw==
    username: AgCSMg2niznYeBuzdmBeFDolW2E6xOpOkhJSFCSfWLgeGSlRZ/9OuhbwxB8bCzWhWqNEi8eIGLIylgzsOJL1j//7BjTyRrqVDFH8VrcRq7SNua80LOIoaZO95kLJK/vvj5ea1qtvZZMMP9PjGCP2VbWg2u3hcsWr9fUYOutv7IY47ScJZIQMMiZNtQQQJagWUvvodsFp/LzCNCGmr96oyon33BZHbCH+bl4L9rMtH9g57WzOFB5/BNd0r/wP6sbNxIiFkZ52BdPGQQVBKRNOC3ZC/UjQQRQjmGx3Ru9qziowWja7JEbadC0hiwVZm2gyy7BzVHPV+9vv5tuyzKev+g33ZafzxwsLCOdWwL7CxvA09khYvk0l4LOSBs25uswcU0N3Uh0eSg1SnmzWH6Izbhw0G34hPM/4Hbkzy8nlYRR1QWE2v6YGBF6uSwcZqS3Bn8TXBRXDwt4ZYytgY9ECCp9vg9zML5BfdmbBcP0zAuXRNkhkg5LccqdrN1ivWV8I3oGp+66BSNQR3moHZNND0wKaTK9r6mKMbSpdLAm7oVf5ZnAjT+mzLYoa4BTOivzLtOFdRnYNbJJhh0g1GzwmjUlzUgxnfxGp5OdnnH+oWZMRbC18oG67G4dwStSHCS9PoSglRy6ztTVKivQpSt0p+Y0u5qE2Gs1oC+OVleMhnJq7dLOaKR6EOG5XWe1WUv0WtpoaMQIokg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

