apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-builtin-admin
  namespace: default
spec:
  encryptedData:
    password: AgAovo36NZRSaL507oUsvxxyqDhfnThP42iFtHb9Cv4JpFbusvFRN3H9RDqdxzgIlgeltjxmdc9lNg5EoaaUqVain9MPbRkaYd2acz8Ob5+WfhJcGvImek5DCYpuPy7NWnTpZ1EXirh2mD5aoGT16ihxIMlsrukGKunNjWGmEWoEpaSmPyyNwVE0k5wrYsPsOEh7ycKw37FrzJxVAvpTUDU5yYrh5ghvkh4+UmcFID37bdLqfRlH1RjUYeKMmgOp2CnNIamCiR+Z4gY1W/QKu3WzYGubJhXJFHwt6T3lvcN0YCS1S+APTR3QIaSPEYujwOka1OrsZXZR6ZOEYivmX4B92I/ofg7+xzRsYtKlcqu3Ndj0V9OnH8NbsrBtmUOia42DRtosFeFzSNljKxAANw7LxpHkfDsGnmO1gijZ6M6XmJ9/lRnwJ7M9eYyWSmpcEm6NzL4FHkmHHWwFWHS8snNSHg+G90aiZ4EzhR6FbEyvAKN87NzFdYrDCSvSq7aTbxUVhCKNXN9PTjsRqPpAfVQT3J+vev1sfhLsXdQZqXvm2qGob0qYHQbniEEw2bVQLOMwZiMDMoz+F+IkQD5i2TDCR6TUjkJvDf9QGJyU5xHalIOHrHB/oEJnjPg/NptoiQm3u8al1mnMfUWjuS+loDr/0y/1LwrGPce/C6vPXxGNNgPpxklzFbZXGdbwsjkqBUeDbw==
    username: AgCIzYFA7QO4HV66riuq8UaLbnySsiFay48KRsEy7mgO+kHMm8rT3KxxLiQH9frVh3OvTImegZX4KSv3XQSMCdZbtxRmEl8tdrFd3y/7HrQAm7Pjy1D7/qAeQZvSTN3Hn0a/CbGA8juuRQvvmUgqL/mfzWnxQa6NLQtu5xkssXev0IKvltBkGEs1CFQvgd/vqVcF5I/k3jq+TWcxZBeJVYPPQ0w1nXNDz6pctPdtV88VwmL93l/yPQuBslJuzRDY88RVV1d5huv5TsTags+EWqVxxlpMJh3q8Xg1IGpj+AEaHDkBJFijX311ofVg7vpocHMQS2W0egeu6JnL1WhIxwvx4w51CYmnPHVsnENsfdp5nhebNMRwW9Mg+/RRtVD3+8yKpS896ZYHBlk7810oCIYzn8EPlU0cQU/z27QDGteot01DJ4hhY5Tq1V2euTGrRj4uubFbC9mQK5kqKnQLs4kDa1eiwBICNKhT6rrzCv4y+dv3Dq8PBfRmSYhMPSMlosleutjNGs4n0zQFRYQo8+26VTBSja0Q7UivNzZx5TH3Ok7EsKbWgQ/4dOau83PQUkCs+OtW4SDKku7stDSAk4o1UAEDyB8OETonpQOtqd96R2II5GkRAmo6sQV5dNC9mVz8Qqigd4LZ0M5BtRJS0Uf4MxiqiiTVGQOw3mvmHKAQmV2vMQi5rjsjHGSp3z1lnVQuHgBOrA==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: keycloak-builtin-admin
      namespace: default
    type: Opaque

