apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


configurations:
- name-refs.yaml

# Add the annotations below to every Secret Kustomize generates.
generatorOptions:
  annotations:
    # Make Sealed Secrets Controller override each dummy Secret we generate
    # with the actual Secret extracted from the corresponding SealedSecret.
    # (Controller won't override an existing Secret unless the Secret has
    # this annotation.)
    sealedsecrets.bitnami.com/managed: "true"

secretGenerator:
- name: keycloak-builtin-admin
  type: Opaque
  literals:
  - version=3


resources:
- keycloak-builtin-admin.yaml


# kubeseal -o yaml < templates/keycloak-builtin-admin.yaml > keycloak-builtin-admin.yaml
# git restore templates
# git add, commit, push
# or
# kustomize build deployment | kubectl apply -f -
#
# maintenance
# kubectl delete sealedsecret/*
# redeploy


# grep -R --exclude-dir=secrets 'keycloak-bui' deployment | cut -f 1 -d ' ' | uniq | sort
