apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-users
  namespace: default
spec:
  encryptedData:
    postgres.password: AgAMZclva41w5rUlxcU5IRTtvisRO13c6oLzk8hweAb4qtrEYV3xCQthH5mTtTkzw4q+7QBVJI07nWDAZQCbcm2nmOh9imAllY2+efY7nVpA7RFET77MDW10UvXIW37m3uTSVY//8c49unJF7rIx8hyUEOB9eys0codlC+bBGOUzGk//NFOjr3hL6lKf7I+6d0BW2PoUC8v1o9Js4D2rGduQyNtyzQVDbIR/hzc/pAcAZmaOvC+DUUk++DkDIb2tn5P+0gJ0B9aQQRmQTr/qyFtOpUT33J+Sep5oUTCCN97/q2xcFwmAhK1/jB0ExGtqJIsE5csAMdT25aWha3KRT4bzDhiSwiHSMcyXNM3mv2+Pr3nEklwoayoIAlUAFYzaIHAaqhdRgfpiQBhtg3+sNySqhUNw+FBuRFA93ZCt6DEeJwcSst+wPI6F/eHj281MRTSgPX90wd2K0caDiXqppSWF6xygqxL6l8WcuXRPkfC9gtuQFREGv0Rl0qJITe9PvWSXDHsgpKnugBfbpVSVrh+XLuWKkGQBdTd+lCh8ZdcxT0OACa6QKaKoP62Zl1nlhDvw+oH6OQ8AH4OpwR+9dO3gD37Ih3UjzZNsGxsftT9WYMnDSxm/uSznFtJF4bgKsQo6ZeO1sl57lpdU26C++bCc/aYkPp32C1M0b3/MGMrTA8uXoCuahptcYlTkBVjmn8DUuzVV12INkEeGb0Im
    quantumleap.password: AgBNv3jrJu4rfANKItJJI+05aPQDC2AwOXiYe5QztkXhg8rfd8jdu8UgI0kVUIxGLR3kPzpvERUbjJ62zfyHAIZAp8O9A++GS6EjDLaaTh4HUNFOhs5lR2NLJgwx1TVqMM4GY0MzkRAhdHm9ihPplqi03xwPRRIp/jOQlntrmDuV3MMTdSF9/NMZUc0NJwLjV0dbwYnnyBrdqJzl0SyQneCDOH1MOWgEOROmuT29IAtow5ult7a/CbYeIgjqfw+guTPaiZAo+pMwTgtiLuATEAbZaEWjcMeDYU6bRNiEjuyx1b23ubMEbUjddCCpT9udgZ0tufpDKHzo5/iEnCyIQ8aeZbFvwc+SocXKmiTx0S3YEnvAlkQOCP7HpVLPg1UHB3ghMNgjMlkHYbLnFpsfC8hpXLGQTPKQx30QP3wXSfN6oYZZJW6prn5WnwGG3mfhsMW5C/0mB/u8hDx3ilQjkt8Fghy70JPz/NbHfPULVFE04O6i2IOOMlJmKPKDoNKHprE3Oh1Sca/ZQlLWYjshDtqmPH5fcGFcx4d3D6FPy5rSDFoOidvVp3Ofky/oZ5xGMHNn3EzE13QWHaUayMgh0MTZu0UFxw4y0lN58UQjuy94Cr6b/lTqTQnYIn0/g/6jV3HPV9o+/ZLImX3bh3lKMuTmcUFy89RTjYEffdUw1RfU6nfudpIvxkp9tqRiLYXDe1XY8cuusTOi8ijmWyDc
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: postgres-users
      namespace: default
    type: Opaque

