apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-users
  namespace: default
spec:
  encryptedData:
    postgres.password: AgCOSUF0wEpF8J4HhB9ZCzPvbhwjYMKTPSlEAAxJGFhOdl1YHHLMP0hHJ69lY0iAuKTa2KOQtoPXyxpnacJbYWuWr6IrFPR9+9bKykwl8wIiZPYqx+6iLmDBHRYewWPS4SqwnpqdskGYVlEjkfjTtHxaRy5G6GaZhd0a6dkS1EmFkvkRRfD9SA5RtTVevE+HEEU2qiUE7LVtrk979KGnPPqhOpC0vQjI07w/sv4pljJz/oKdlQO2p7lTws9ElXGs837L7DQrZb3k0nQT8iJatFV34qPCYRTiB5AiRIQ/c0KnQE4L1IN1d4mS19F/Lx4mBFOrSW5sgDXki1imp2OV321TtdBX1lxZrr2hdQmAqJ4a948+tMadFoa3F+NZY7wibzsmdPmIoTQJa7ww3WpcqwRPR36FUkDOVAeiD3hf5JbvM8+MWtVQF8cqmfqHf0SPzOU1Q4nQVYaaIO4gdxFBPBv3YYMpyTZJlWU9lUvusZryFvkFH+qMncNsUZcd/M+077KMJbsIRBUcbFES9JwgfVES1ONwAz+kO/zCaFAGVJKo0P1kClt2UfkqmEwx3yFp/h6S+EE7F0gvmVJyvT5KBYeJfkzqAiQzMTyEX6LqlkpBvJl8oIx5lDscnwPMZNv0hc7ammacDWloeFcqkorSbti07Ro3ILHRp89s72t0DXgDIWswVARtF2bD3GD1tOdYEVEWCb5x19J1gDpHBgN3KtxfqD0Wcrp3tyu/SRE=
    quantumleap.password: AgAuQ3b1BVRrcel8LrpcQay+JOsbxdW/Qc+vrgvMrrc/0+4AznMGULCqSSP9ti3psaxOCbJ8KCOit75MAysNoTUF1Y1lR10c8Exa6HUpIx2zFh0JYcWIOzL+T0bFSwmT7fRFpbMnBR1seKBAr6OIsbvEWYpDm76rj+P4j3/jwNrnW8+9vJ2SBPiqM41+GIR9jIFRTLKjEUFqYB6m65QcwT3J3WK8hzeaeIFwhWq1jummYHj7UYxKvs/PppqOUDesKFoGAh0khYCwtf5X17fIjRtFuogX65HptAxNfvb/xj0uk2wOm8K63ajw0qpaptKeP/4FsGChlhzutXd8o9LwtSR9SpbqXbRGWeETkLjI/4v8CRjvx+wF0rbdvnelGbkhu2Sf2/GwKiVwJlZp1sxnaOGzUcEcVt2fs+AdZqrrOyOjuqRkt/yW5hunNps+zB90gCzeU1dpCZavjtULbgQ1iXoyKmOiluIWA2po0B6gcLeFsEULDK+217aNMrh/kiryE48+6wGfCXEC2ECWw2qyYvMDhHYfHngcDBa7eVY4YMyRTQ/q84mUFbhrOhP9p0+OcgPlWG6XztHcU1LOoF0G/Th1VViLUXtcpW30GoLJ1fQkqJ3hwcO8rOjYxWi97v9TuASkF7QjHEAEItkY9HdKnB6XUHxpQIMX53E78lyT7UFAy40UVoiBCjV5W9upeCdjBfbFFDIg6dfbvYFDCpaX60CkP0phdhh3T2x6n64=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: postgres-users
      namespace: default
    type: Opaque

