apiVersion: v1
kind: Service
metadata:
  labels:
    app: viqe
  name: viqe
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: viqe

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: viqe
  name: viqe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viqe
  template:
    metadata:
      labels:
        app: viqe
    spec:
      containers:
        - image: "ghcr.io/c0c0n3/kitt4sme.viqe:0.1.0"
          imagePullPolicy: IfNotPresent
          name: viqe
          ports:
          - containerPort: 8000
            name: http
          env:
          - name: "QUANTUMLEAP_BASE_URL"
            value: "http://quantumleap:8668"
